[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
safnect = "9fxtdVYDHPh9qm34FL6d6aLJ4Hztc28BvGnGMn3aWXEF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/superatom/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
